/**
 * buildThemes.ts — 扫描 themes/*.yaml，生成 tokens.css
 * 支持 slots.yaml 中的 {token-ref} 引用解析
 * 用法：npx tsx src/shared/themes/buildThemes.ts
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const themesDir = path.resolve(__dirname);
const outFile = path.resolve(__dirname, '../styles/tokens.css');

const staticTokens = `
  --font-ui: "Inter", "Noto Sans SC", "PingFang SC", "Microsoft YaHei", "Segoe UI", sans-serif;
  --font-display: "Newsreader", "Noto Serif SC", "Songti SC", "SimSun", "Georgia", serif;
  --inspector-width: 300px;
`;

function loadYaml(filePath: string): Record<string, string> {
  if (!fs.existsSync(filePath)) return {};
  return (yaml.load(fs.readFileSync(filePath, 'utf-8')) as Record<string, string>) || {};
}

function resolveSlots(slots: Record<string, string>, palette: Record<string, string>): Record<string, string> {
  const resolved: Record<string, string> = {};
  for (const [key, val] of Object.entries(slots)) {
    const match = val.match(/^\{(.+)\}$/);
    if (match) {
      const ref = match[1];
      resolved[key] = palette[ref] ?? `var(--${ref})`;
    } else {
      resolved[key] = val;
    }
  }
  return resolved;
}

function toVars(obj: Record<string, string>): string {
  return Object.entries(obj)
    .map(([key, val]) => `  --${key}: ${val};`)
    .join('\n');
}

// Load palette themes (light.yaml, dark.yaml)
const paletteFiles = fs.readdirSync(themesDir).filter(
  (f) => f.endsWith('.yaml') && !f.startsWith('slots')
);
const palettes: Record<string, Record<string, string>> = {};
for (const file of paletteFiles) {
  const name = path.basename(file, '.yaml');
  palettes[name] = loadYaml(path.join(themesDir, file));
}

// Load slots
const slotsBase = loadYaml(path.join(themesDir, 'slots.yaml'));
const slotsLightOverride = loadYaml(path.join(themesDir, 'slots.light.yaml'));
const slotsDarkOverride = loadYaml(path.join(themesDir, 'slots.dark.yaml'));

// Resolve slots for each palette theme
function buildThemeVars(paletteName: string): string {
  const palette = palettes[paletteName];
  if (!palette) return '';
  const override = paletteName === 'dark' ? slotsDarkOverride : slotsLightOverride;
  const slots = { ...slotsBase, ...override };
  const resolvedSlots = resolveSlots(slots, palette);
  return toVars({ ...palette, ...resolvedSlots });
}

const light = palettes['light'];
if (!light) {
  console.error('Error: light.yaml is required as the base theme');
  process.exit(1);
}

let css = `/* Auto-generated by buildThemes.ts — DO NOT EDIT */\n\n`;

// :root uses light theme + slots + static tokens
css += `:root {\n  color-scheme: light;\n${buildThemeVars('light')}\n${staticTokens}}\n\n`;

// Each palette theme gets a [data-theme] selector
for (const name of Object.keys(palettes)) {
  const scheme = name === 'dark' ? 'dark' : 'light';
  css += `[data-theme="${name}"] {\n  color-scheme: ${scheme};\n${buildThemeVars(name)}\n}\n\n`;
}

// system theme follows prefers-color-scheme
if (palettes['dark']) {
  css += `@media (prefers-color-scheme: dark) {\n  [data-theme="system"] {\n    color-scheme: dark;\n${buildThemeVars('dark')}\n  }\n}\n`;
}

// Global reset
css += `\n* {\n  box-sizing: border-box;\n}\n\nhtml,\nbody,\n#root {\n  margin: 0;\n  min-height: 100%;\n}\n\nbody {\n  background: var(--background);\n  color: var(--on-surface);\n  font-family: var(--font-ui);\n}\n`;

fs.writeFileSync(outFile, css, 'utf-8');
console.log(`Generated ${outFile} with ${Object.keys(palettes).length} theme(s) + slots`);

export { loadYaml, resolveSlots, buildThemeVars, toVars, palettes, slotsBase, slotsDarkOverride, outFile };
