import { describe, expect, it, vi } from 'vitest';

vi.mock('electron', () => ({
  contextBridge: { exposeInMainWorld: vi.fn() },
  ipcRenderer: { invoke: vi.fn(), send: vi.fn() },
  webUtils: { getPathForFile: vi.fn() }
}));

import { exposedDesktopApi } from '../preload/index';

describe('preload security surface', () => {
  it('only exposes the whitelisted desktop api', () => {
    expect(Object.keys(exposedDesktopApi).sort()).toEqual([
      'abortAgentRun',
      'acceptSettingMdPatch',
      'applyAgentFieldPatch',
      'applyAuthorProfileNote',
      'canaryProbeVision',
      'checkForUpdate',
      'clearWallpaper',
      'close',
      'compactAgentSession',
      'compileRevisionIntent',
      'confirmClose',
      'copyCoverImage',
      'createAgentSession',
      'createEntry',
      'createProjectDirectory',
      'deleteAgentSession',
      'deleteAsset',
      'deleteEntry',
      'deleteProject',
      'deleteProjectFile',
      'deleteTask',
      'docxToHtml',
      'docxToMarkdown',
      'downloadUpdate',
      'duplicateProject',
      'ensureProjectDocument',
      'ensureProjectRegistration',
      'executeAgentSkill',
      'generateEmbedding',
      'generateImage',
      'generateText',
      'getAgentSession',
      'getAppVersion',
      'getIndexStatus',
      'getLocale',
      'gitCheckoutBranch',
      'gitCommitDiff',
      'gitCreateBranch',
      'gitCreateNode',
      'gitCurrentBranch',
      'gitFileAtCommit',
      'gitInit',
      'gitIsRepo',
      'gitListBranches',
      'gitLog',
      'gitRestoreVersion',
      'gitStatusCount',
      'importAssets',
      'importDocx',
      'importFiles',
      'importFonts',
      'importWallpaper',
      'installUpdate',
      'isKeyEncryptionAvailable',
      'isMaximized',
      // C1.2 llmlint：三 lint 通道（scan-full / classify / apply-fix）+ 判档探测（CR-014）。
      'lintApplyFix',
      'lintClassify',
      'lintModelProbe',
      'lintScanFull',
      'listAgentContinuations',
      'listAgentSessions',
      'listAgentSkills',
      'listAssets',
      'listImportedFonts',
      'listRegisteredProjects',
      'listRemoteModels',
      'listSkillPackages',
      'listTasks',
      'loadModelConfig',
      'loadProjectDocument',
      'loadProjectMeta',
      'loadResearchConfig',
      'loadUserPreferences',
      'maximize',
      'minimize',
      'moveProjectFile',
      'onAgentStreamEvent',
      'onBeforeClose',
      'onToolEvent',
      'onUpdateEvent',
      'openExternal',
      'openLogsDir',
      'openPath',
      'pathExists',
      'pathForFile',
      'pickCoverImage',
      'pickProjectDirectory',
      'platform',
      'probeResearchDocParser',
      'readDirectory',
      'readFile',
      'readFileBinary',
      'rebuildCraftKb',
      'rebuildStoryIndex',
      'renameEntry',
      'renameProject',
      'rerank',
      'resolveAgentConfirmation',
      'restoreAgentContinuation',
      'resumeChapterChain',
      'runChapterChain',
      'runStorySync',
      'saveBase64Image',
      'saveModelConfig',
      'saveProjectMeta',
      'saveResearchConfig',
      'saveUserPreferences',
      'searchProject',
      'setAgentSessionBehaviorMode',
      'setAgentSessionMode',
      'setAgentSessionParticipationGear',
      'setPackageEnabled',
      'setSkillEnabled',
      'showItemInFolder',
      'streamAgentMessage',
      'syncChaptersMeta',
      'syncField',
      'syncProjectMeta',
      'toggleFieldLock',
      'touchProjectRegistration',
      'truncateAgentSession',
      'unwatchProject',
      'updateAsset',
      'updateTaskStatus',
      'upsertAsset',
      'upsertTask',
      'watchProject',
      'wordCount',
      'writeFile',
      'writeLog',
    ]);
  });

  it('does not expose any apiKey-bearing function on the renderer surface', () => {
    // The whitelisted IPC handlers move slot pairs (profileId, modelId) across
    // IPC; apiKey lives in desktop main's safeStorage and is decrypted only
    // there. Renderer never sees it.
    const apiKeys = Object.keys(exposedDesktopApi).filter((key) => /apiKey/i.test(key));
    expect(apiKeys).toEqual([]);
  });
});
