name: Feature request
description: Suggest an idea for Closure
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: >-
        What problem does this feature solve? What are you trying to do? If it
        relates to an item on the README roadmap, mention which one.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like to happen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or features you've considered.
