import { defineConfig, externalizeDepsPlugin } from 'electron-vite';
import react from '@vitejs/plugin-react';
import path from 'node:path';
import fs from 'node:fs';
import yaml from 'js-yaml';

const desktopUiSrc = path.resolve(__dirname, '../ui/src');
const bundledWorkspaceDeps = ['@orison/shared-contracts', '@orison/model-protocols', '@orison/story-sync', '@orison/desktop-agent', '@orison/desktop-local-bff'];

const themesDir = path.resolve(desktopUiSrc, 'shared/themes');
const tokensOut = path.resolve(desktopUiSrc, 'shared/styles/tokens.css');

function loadYaml(filePath: string): Record<string, string> {
  if (!fs.existsSync(filePath)) return {};
  return (yaml.load(fs.readFileSync(filePath, 'utf-8')) as Record<string, string>) || {};
}

function resolveSlots(slots: Record<string, string>, palette: Record<string, string>): Record<string, string> {
  const resolved: Record<string, string> = {};
  for (const [key, val] of Object.entries(slots)) {
    const match = val.match(/^\{(.+)\}$/);
    if (match) {
      const ref = match[1];
      resolved[key] = palette[ref] ?? `var(--${ref})`;
    } else {
      resolved[key] = val;
    }
  }
  return resolved;
}

function buildTokensCss() {
  const staticTokens = `
  --font-ui: "Inter", "Noto Sans SC", "PingFang SC", "Microsoft YaHei", "Segoe UI", sans-serif;
  --font-display: "Newsreader", "Noto Serif SC", "Songti SC", "SimSun", "Georgia", serif;
  --inspector-width: 300px;
`;
  const paletteFiles = fs.readdirSync(themesDir).filter(
    (f) => f.endsWith('.yaml') && !f.startsWith('slots')
  );
  const palettes: Record<string, Record<string, string>> = {};
  for (const file of paletteFiles) {
    const name = path.basename(file, '.yaml');
    palettes[name] = loadYaml(path.join(themesDir, file));
  }
  const slotsBase = loadYaml(path.join(themesDir, 'slots.yaml'));
  const slotsLightOverride = loadYaml(path.join(themesDir, 'slots.light.yaml'));
  const slotsDarkOverride = loadYaml(path.join(themesDir, 'slots.dark.yaml'));

  function buildThemeVars(paletteName: string): string {
    const palette = palettes[paletteName];
    if (!palette) return '';
    const override = paletteName === 'dark' ? slotsDarkOverride : slotsLightOverride;
    const slots = { ...slotsBase, ...override };
    const resolvedSlots = resolveSlots(slots, palette);
    const all = { ...palette, ...resolvedSlots };
    return Object.entries(all).map(([k, v]) => `  --${k}: ${v};`).join('\n');
  }

  if (!palettes['light']) return;
  let css = `/* Auto-generated by buildThemes — DO NOT EDIT */\n\n`;
  css += `:root {\n  color-scheme: light;\n${buildThemeVars('light')}\n${staticTokens}}\n\n`;
  for (const name of Object.keys(palettes)) {
    const scheme = name === 'dark' ? 'dark' : 'light';
    css += `[data-theme="${name}"] {\n  color-scheme: ${scheme};\n${buildThemeVars(name)}\n}\n\n`;
  }
  if (palettes['dark']) {
    css += `@media (prefers-color-scheme: dark) {\n  [data-theme="system"] {\n    color-scheme: dark;\n${buildThemeVars('dark')}\n  }\n}\n`;
  }
  css += `\n* {\n  box-sizing: border-box;\n}\n\nhtml,\nbody,\n#root {\n  margin: 0;\n  min-height: 100%;\n}\n\nbody {\n  background: var(--background);\n  color: var(--on-surface);\n  font-family: var(--font-ui);\n}\n`;
  fs.writeFileSync(tokensOut, css, 'utf-8');
}

function themeHotPlugin() {
  return {
    name: 'orison-theme-hot',
    buildStart() { buildTokensCss(); },
    configureServer(server: { watcher: { add(p: string): void; on(e: string, cb: (f: string) => void): void } }) {
      server.watcher.add(themesDir);
      server.watcher.on('change', (file) => {
        if (file.startsWith(themesDir) && file.endsWith('.yaml')) {
          buildTokensCss();
        }
      });
    },
  };
}

// C1.2 llmlint（Step 7a rulesets 生产路径）：vendored 引擎以 `import.meta.url` 相对定位
// rulesets/（vendor rules.ts 的 RULESETS_ROOT）。dev（tsx）/vitest 下指向 agent 源码树正确；
// 但 shell 的任何 bundle 运行形态（electron-vite dev 与打包产物都在 dist/main 跑）下
// rollup 会把 `import.meta.url` 改写为 `pathToFileURL(__filename).href`，模块内目录结构坍缩
// ——RULESETS_ROOT 解析为 `<shell>/dist/rulesets`（所有 main chunk 平铺在 dist/main，dirname
// 一致）。本插件把 vendored rulesets 拷到 `dist/rulesets`，让**默认解析在三种上下文全部成立**
// （agent vitest 源码树 / shell dev bundle / 打包 asar——Electron 的 asar fs shim 支持
// readFile/readdir/stat/exists，JSON 只读无碍），vendored 代码零修改。
// dist/** 本就是 electron-builder `files` 条目（主 bundle 自身从那里发货）——拷贝产物必然
// 打包，完全绕开 craft-KB 漏建 extraResources 的先例债（无需任何 extraResources 配置）。
// 拷到 dist/rulesets（dist/main 之外）以避开 vite 对 outDir 的清空。
const lintRulesetsSrc = path.resolve(__dirname, '../../agent/src/lint/vendor/llmlint/rulesets');

function lintRulesetsCopyPlugin() {
  return {
    name: 'orison-lint-rulesets-copy',
    buildStart() {
      fs.cpSync(lintRulesetsSrc, path.resolve(__dirname, 'dist', 'rulesets'), { recursive: true });
    },
  };
}

export default defineConfig({
  main: {
    plugins: [externalizeDepsPlugin({ exclude: bundledWorkspaceDeps }), lintRulesetsCopyPlugin()],
    build: {
      outDir: 'dist/main',
      lib: {
        entry: path.resolve(__dirname, 'main/index.ts'),
        formats: ['cjs']
      },
      rollupOptions: {
        output: {
          entryFileNames: '[name].cjs'
        }
      }
    }
  },
  preload: {
    plugins: [externalizeDepsPlugin({ exclude: bundledWorkspaceDeps })],
    build: {
      outDir: 'dist/preload',
      lib: {
        entry: path.resolve(__dirname, 'preload/index.ts'),
        formats: ['cjs']
      },
      rollupOptions: {
        output: {
          entryFileNames: '[name].cjs'
        }
      }
    }
  },
  renderer: {
    root: path.resolve(__dirname, 'renderer'),
    plugins: [react(), themeHotPlugin()],
    build: {
      outDir: path.resolve(__dirname, 'dist/renderer'),
      rollupOptions: {
        input: path.resolve(__dirname, 'renderer/index.html')
      }
    },
    resolve: {
      alias: {
        '@desktop-ui': desktopUiSrc
      }
    }
  }
});
